# Generated by Django 4.1 on 2022-12-10 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_annual', models.PositiveIntegerField(default=0, verbose_name='Annual Leave')),
                ('leave_sick', models.PositiveIntegerField(default=0, verbose_name='Sick Leave')),
                ('leave_work_home', models.PositiveIntegerField(default=0, verbose_name='Work From Home')),
                ('leave_maternity', models.PositiveIntegerField(default=0, verbose_name='Maternity Leave')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
