# Generated by Django 4.1 on 2022-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0002_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_annual',
            field=models.PositiveIntegerField(default=18, verbose_name='Annual Leave'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_sick',
            field=models.PositiveIntegerField(default=100, verbose_name='Sick Leave'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_work_home',
            field=models.PositiveIntegerField(default=20, verbose_name='Work From Home'),
        ),
    ]
