# Generated by Django 4.1 on 2022-12-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0003_alter_leavebalance_leave_annual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_annual',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_maternity',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_sick',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_work_home',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='starting_leave_annual',
            field=models.PositiveIntegerField(default=18, verbose_name='Starting Balance - Annual Leave'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='starting_leave_maternity',
            field=models.PositiveIntegerField(default=0, verbose_name='Starting Balance - Maternity Leave'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='starting_leave_sick',
            field=models.PositiveIntegerField(default=100, verbose_name='Starting Balance - Sick Leave'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='starting_leave_work_home',
            field=models.PositiveIntegerField(default=20, verbose_name='Starting Balance - Work From Home'),
        ),
    ]
