# Generated by Django 4.1 on 2022-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0004_remove_leavebalance_leave_annual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='used_leave_annual',
            field=models.PositiveIntegerField(default=18, verbose_name='Used Balance - Annual Leave'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_leave_maternity',
            field=models.PositiveIntegerField(default=0, verbose_name='Used Balance - Maternity Leave'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_leave_sick',
            field=models.PositiveIntegerField(default=100, verbose_name='Used Balance - Sick Leave'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_leave_work_home',
            field=models.PositiveIntegerField(default=20, verbose_name='Used Balance - Work From Home'),
        ),
    ]
