# Generated by Django 4.1 on 2022-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0007_leavebalance_planned_leave_annual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='dept_manager',
            field=models.BooleanField(default=False),
        ),
    ]
