# Generated by Django 4.1 on 2022-12-21 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0008_myuser_dept_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dept_manager',
            field=models.BooleanField(default=False, verbose_name='Department Manager'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('Work From Home', 'Work From Home'), ('Maternity Leave', 'Maternity Leave')], default='Annual Leave', max_length=32)),
                ('leave_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
