# Generated by Django 4.1 on 2023-01-04 04:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0009_alter_myuser_dept_manager_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_start',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_until',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
