# Generated by Django 4.1 on 2023-01-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_system', '0010_remove_leave_leave_date_leave_leave_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_reason',
            field=models.CharField(default='No reason given.', max_length=128),
        ),
    ]
